### ISSUE TITLE
Create `elixir_auth_facebook` v1

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-facebook#21]
Let's get this built!

# Todo

+ [ ] Create a **`new` `mix`** project 🆕 
+ [ ] Borrow as much code as possible/practical from our previous work. ♻️ 
  + Google: https://github.com/dwyl/elixir-auth-google 📱 
  + GitHub: https://github.com/dwyl/elixir-auth-github :octocat: 
+ [ ] Write-up _detailed_ documentation similar to https://github.com/dwyl/elixir-auth-google ✍️ 
+ [ ] Publish the **`hex.pm`** project under the **dwyl** org. :shipit:

**Comment by ndrean** [comment]
OK. Done the SSR. 10h!!! Couldn't find how to reach for the profile endpoint. Definitely more work to do than using the Facebook snippet client-side.
Saying that I never use FB😏 but it is so convenient to have it.

My draft will follow.

**Comment by ndrean** [comment]
```elixir
defmodule ElixirAuthFacebook do
  @moduledoc """
Snippet to get a Facebook Login link in four steps:

You add a link, say in your index.html:
<a class="" href={@oauth_facebook_url}>
  <img src={Routes.static_path(@conn, "/images/fb_login.png")} style="margin-left: 120px;"/>
</a>

So you declare a route:
get "/auth/facebook/callback", FacebookAuthController, :index

thus build a controller FacebookAuthController:
{:ok, profile, user_data} = ElixirAuthFacebook.handle_callback(conn, params)

Then have fun with <https://developers.facebook.com/apps/?show_reminder=true>
  """

  @default_callback_path "https://localhost:4443/auth/facebook/callback"
  @default_scope "public_profile"
  @auth_type "rerequest"
  @fb_dialog_oauth "https://www.facebook.com/v15.0/dialog/oauth?"
  @fb_access_token "https://graph.facebook.com/v15.0/oauth/access_token?"
  @fb_debug "https://graph.facebook.com/debug_token?"
  @fb_profile "https://graph.facebook.com/v15.0/me?fields=id,email,name,picture"

  @doc """
  Generate URI for first access with temporary "code" from users' credentials.
  We also inject a "salt" and the APP_ID and we check if our "salt" is happily returned
  """
  def generate_oauth_url() do
    @fb_dialog_oauth <> params_1()
  end

  @doc """
  Generate URI for second query to receive the access_token from the "code"
  """
  def get_access_token(params) do
    @fb_access_token <> params_2(params)
  end

  @doc """
  Third query to verify.
  """
  defp debug_token(token) do
    @fb_debug <> params_3(token)
  end

  @doc """
  Fetch user's profile
  """
  def graph_api(), do: @fb_profile

  @doc """
  Function to document how to terminate errors. Use flash, redirect...
  """
  def terminate(conn, message, path) do
    conn
    |> Phoenix.Controller.put_flash(:error, inspect(message))
    |> Phoenix.Controller.redirect(to: path)
    |> Plug.Conn.halt()
  end

  def handle_callback(conn, %{"error" => error}) do
    terminate(conn, error, "/")
  end

  @doc """
  We receive the "state" aka as "salt" we sent.
  """
  def handle_callback(conn, %{"state" => state} = params) do
    keys = Map.keys(params)

    with {:salt, true} <- {:salt, check_salt(state)},
         {:code, true} <- {:code, "code" in keys} do
      fb_oauth = get_access_token(params)

      case HTTPoison.get(fb_oauth) do
        {:error, %HTTPoison.Error{id: nil, reason: err}} ->
          terminate(conn, err, "/")

        {:ok, %HTTPoison.Response{body: body}} ->
          conn
          |> decode_body(body)
          |> get_login()
          |> get_profile()
      end
    else
      {:salt, false} ->
        terminate(conn, "salt false", "/")

      {:code, false} ->
        terminate(conn, "code false", "/")
    end
  end

  def decode_body(conn, body) do
    Plug.Conn.assign(conn, :body, Jason.decode!(body))
  end

  def get_login(%Plug.Conn{assigns: %{body: %{"error" => %{"message" => message}}}} = conn) do
    terminate(conn, message, "/")
  end

  def get_login(%Plug.Conn{assigns: %{body: %{"access_token" => token}}} = conn) do
    case HTTPoison.get(debug_token(token)) do
      {:ok, %HTTPoison.Response{body: body}} ->
        IO.inspect(body, label: "get_login")

        case Jason.decode!(body) do
          %{"error" => %{"message" => message}} ->
            terminate(conn, message, "/")

          %{"data" => data} ->
            %{"user_id" => fb_id, "is_valid" => valid, "expires_at" => exp} = data

            conn
            |> Plug.Conn.assign(:token, token)
            |> Plug.Conn.assign(:exp, exp)
            |> Plug.Conn.assign(:valid, valid)
            |> Plug.Conn.assign(:fb_id, fb_id)
        end

      {:error, %HTTPoison.Error{id: nil, reason: err}} ->
        terminate(conn, err, "/")
    end
  end

  @doc """
  <https://developers.facebook.com/docs/graph-api/reference/user/>
  """

  def get_profile(%Plug.Conn{assigns: %{valid: false}} = conn) do
    terminate(conn, "renew your credentials", "/")
  end

  def get_profile(%Plug.Conn{assigns: %{token: token, fb_id: fb_id, exp: exp}} = conn) do
    params = %{"access_token" => token} |> URI.encode_query()
    me_point = graph_api() <> "&" <> params

    case HTTPoison.get(me_point) do
      {:error, %HTTPoison.Error{id: nil, reason: err}} ->
        IO.inspect(err, label: "error")

        terminate(conn, err, "/")

      {:ok, %HTTPoison.Response{body: body}} ->
        %{"email" => email, "id" => fb_id, "name" => name, "picture" => avatar} =
          Jason.decode!(body)

        profile = %{
          email: email,
          fb_id: fb_id,
          name: name,
          avatar: avatar
        }

        user_data = %{token: token, exp: exp, fab_id: fb_id}
        # |> PROPOSE TO USER TO SAVE TO DATABASE

        {:ok, profile, user_data}
        # conn
        # |> Plug.Conn.put_session(:user_data, user_data)
        # |> Plug.Conn.put_session(:profile, Jason.decode!(body))

        # |> terminate("", "/welcome")
    end
  end

  def get_salt() do
    Application.get_env(:live_map, LiveMapWeb.Endpoint)
    |> List.keyfind(:live_view, 0)
    |> then(fn {:live_view, [signing_salt: val]} ->
      val
    end)
  end

  def check_salt(state) do
    get_salt() == state
  end

  defp params_1() do
    %{
      "client_id" => System.get_env("FACEBOOK_APP_ID"),
      "state" => get_salt(),
      "redirect_uri" => @default_callback_path,
      "scope" => @default_scope
    }
    |> URI.encode_query()
  end

  defp params_2(params) do
    %{
      "client_id" => System.get_env("FACEBOOK_APP_ID"),
      "state" => get_salt(),
      "redirect_uri" => @default_callback_path,
      "code" => params["code"],
      "client_secret" => System.get_env("FACEBOOK_APP_SECRET")
    }
    |> URI.encode_query()
  end

  defp params_3(token) do
    %{
      "access_token" => token,
      "input_token" => token
    }
    |> URI.encode_query()
  end
end
```

**Comment by ndrean** [comment]
I used `Caddy` to run HTTPS locally for the client snippet, so the app was reached at <https://localhost:4443>
`caddy run --watch`

```json
#Caddyfile
localhost:4443 {
	handle {
		reverse_proxy * 127.0.0.1:4000
	}
}
```

**Comment by ndrean** [comment]
I will refactor closer to your style with `HTTPoison.get!`.

**Comment by ndrean** [comment]
Closer to your standards I believe with less "case" and more destructuring in the arguments

```elixir
defmodule ElixirAuthFacebook do
  @moduledoc """
  Snippet to enable Facebook Login
  """

  @default_callback_path "https://localhost:4443/auth/facebook/callback"
  @default_scope "public_profile"
  @auth_type "rerequest"
  @fb_dialog_oauth "https://www.facebook.com/v15.0/dialog/oauth?"
  @fb_access_token "https://graph.facebook.com/v15.0/oauth/access_token?"
  @fb_debug "https://graph.facebook.com/debug_token?"
  @fb_profile "https://graph.facebook.com/v15.0/me?fields=id,email,name,picture"

  def app_id(),
    do:
      System.get_env("FACEBOOK_APP_ID") ||
        Application.get_env(:elixir_auth_facebook, :app_id)

  def app_secret() do
    System.get_env("FACEBOOK_APP_SECRET") ||
      Application.get_env(:elixir_auth_facebook, :app_secret)
  end

  def app_access_token(), do: app_id() <> "|" <> app_secret()

  @doc """
  Opens Login dialog. A "state" test is injected to prevent CSRF
  """
  def generate_oauth_url(), do: @fb_dialog_oauth <> params_1()

  @doc """
  Exchange the "code" for an "access_token".
  Sends the APP_SECRET
  """
  def access_token_uri(code), do: @fb_access_token <> params_2(code)

  @doc """
  Third query to inspect Access Token
  """
  def debug_token_uri(token), do: @fb_debug <> params_3(token)

  @doc """
  Last query to fetch user's profile with the Graph API.
  """
  def graph_api(access), do: @fb_profile <> "&" <> access

  @doc """
  Function to document how to terminate errors. Use flash, redirect...
  """
  def terminate(conn, message, path) do
    conn
    |> Phoenix.Controller.put_flash(:error, inspect(message))
    |> Phoenix.Controller.redirect(to: path)
    |> Plug.Conn.halt()
  end

  def handle_callback(conn, params, term \\ &terminate/3)

  # User denies Login dialog
  def handle_callback(conn, %{"error" => message}, term) do
    term.(conn, {:handle_callback, message}, "/")
  end

  @doc """
  We receive the "state" aka as "salt" we sent.
  """
  def handle_callback(conn, %{"state" => state, "code" => code}, term) do
    conn = Plug.Conn.assign(conn, :term, term)

    with {:salt, true} <- {:salt, check_salt(state)} do
      code
      |> access_token_uri()
      |> HTTPoison.get!()
      |> Map.get(:body)
      |> Jason.decode!()
      |> then(fn data ->
        conn
        |> Plug.Conn.assign(:data, data)
        |> get_login()
        |> get_profile()
        |> check_profile()
        |> dbg()
      end)
    else
      {:salt, false} ->
        term.(conn, "salt false", "/")
    end
  end

  def get_login(%Plug.Conn{assigns: %{data: %{"error" => %{"message" => message}}}} = conn) do
    conn.assigns.term.(conn, {:get_login, message}, "/")
  end

  def get_login(%Plug.Conn{assigns: %{data: %{"access_token" => token}}} = conn) do
    token
    |> debug_token_uri()
    |> HTTPoison.get!()
    |> Map.get(:body)
    |> Jason.decode!()
    |> Map.get("data")
    |> then(fn data ->
      conn
      |> Plug.Conn.assign(:data, data)
      |> Plug.Conn.assign(:token, token)
      |> Plug.Conn.assign(:is_valid, data["is_valid"])
    end)
  end

  def get_profile(%Plug.Conn{assigns: %{data: %{"error" => %{"message" => message}}}} = conn) do
    conn.assigns.term.(conn, {:get_profile, message}, "/")
  end

  def get_profile(%Plug.Conn{assigns: %{is_valid: nil}} = conn) do
    conn.assigns.term.(conn, {:get_profile, "renew your credentials"}, "/")
  end

  def get_profile(%Plug.Conn{assigns: %{token: token, is_valid: true}} = conn) do
    URI.encode_query(%{"access_token" => token})
    |> graph_api()
    |> HTTPoison.get!()
    |> Map.get(:body)
    |> Jason.decode!()
    |> then(fn data ->
      Plug.Conn.assign(conn, :profile, data)
    end)
  end

  def check_profile(%Plug.Conn{assigns: %{profile: %{"error" => %{"message" => message}}}} = conn) do
    conn.assigns.term.(conn, {:check_profile, message}, "/")
  end

  def check_profile(%Plug.Conn{assigns: %{token: token, profile: profile}}) do
    profile =
      for({k, v} <- profile, into: %{}, do: {String.to_atom(k), v})
      |> Map.merge(%{token: token})

    {:ok, profile}
  end

  def get_salt() do
    Application.get_env(:live_map, LiveMapWeb.Endpoint)
    |> List.keyfind(:live_view, 0)
    |> then(fn {:live_view, [signing_salt: val]} ->
      val
    end) ||
      raise """
      Missing Endpoint signing salt
      """
  end

  def check_salt(state) do
    get_salt() == state
  end

  defp params_1() do
    URI.encode_query(%{
      "client_id" => app_id(),
      "state" => get_salt(),
      "redirect_uri" => @default_callback_path,
      "scope" => @default_scope
    })
  end

  defp params_2(code) do
    URI.encode_query(%{
      "client_id" => app_id(),
      "state" => get_salt(),
      "redirect_uri" => @default_callback_path,
      "code" => code,
      "client_secret" => app_secret()
    })
  end

  defp params_3(token) do
    URI.encode_query(%{
      "access_token" => app_access_token(),
      "input_token" => token
    })
  end
end
```

**Comment by ndrean** [comment]
Stupid question but... I have no right to push code to a non-existing branch. How do I `git push remote ssr`???

**Comment by nelsonic** [comment]
@ndrean you should have full write access to push your branch. Please confirm. 🤞🏼

**Comment by ndrean** [comment]
“fork and branch” workflow looks something like this:

Fork a GitHub repository.
Clone the forked repository to your local system.
Add a Git remote for the original repository.
Create a feature branch in which to place your changes.
Make your changes to the new branch.
Commit the changes to the branch.
Push the branch to GitHub.
Open a pull request from the new branch to the original repo.
Clean up after your pull request is merged.

**Comment by ndrean** [comment]
I made two branches: SDK and SSR
I believe SDK is ok, not SSR yet.
Can you review it?

**Comment by nelsonic** [comment]
@ndrean please assign PR to me when you feel it's ready for review. 🙏
